config/routes.rb
Rails.application.routes.draw do
  get 'home/about' => 'home#about'
  root to: 'home#top'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  resources :books, only: [:index, :create, :show, :edit, :update, :destroy]
  resources :users, only: [:index, :edit, :show, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  attachment :profile_image
  
  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(resource)
  end
  
  def after_sign_up_path_for(resource)
    user_path(resource)
  end
  
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end
  
  def about
  end
  
  def index
    @user = User.find(current_user.id)
    @books = Book.all
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: 'You have created book successfully'
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.new
    @show_book = Book.find(params[:id])
    @user = User.find(@show_book.user_id)
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id == current_user.id
    else
      redirect_to books_path
    end
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: 'You have updated book successfully'
    else
      render :edit
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end
  
  private
    def book_params
      params.require(:book).permit(:title, :body)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = User.find(current_user.id)
    @book = Book.new
  end
  
  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
    else
      redirect_to user_path(current_user)
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully"
    else
      render :edit
    end
  end
  
  private
    def user_params
      params.require(:user).permit(:name, :profile_image, :introduction)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg"%>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>
  
  <div class="row">
    <%= link_to(edit_user_path(user.id), class: "btn btn-outline-secondary btn-block") do %>
      <i class=" fas fa-user-cog"></i>
    <% end %>
  </div>
  
  <h2 class="mt-3">New book</h2>
  <%= form_with model:@book, local:true do |f| %>
    <div class="form-group">
      <div class="field_with_errors">
        <%= f.label :title, "Title" %>
      </div>
      <div class="field_with_errors">
        <%= f.text_field :title, class: "form-control book_title", id: "book_title" %>
      </div>
    </div>
    <div class="form-group">
      <div class="field_with_errors">
        <%= f.label :body, "Opinion" %>        
      </div>
      <div class="field_with_errors">
        <%= f.text_area :body, class: "form-control book_body", id: "book_body" %>
      </div>
    </div>
    <div class="form-group mt-3 mb-3">
      <%= f.submit 'Create Book', class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/books/edit.html.erb
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  <h1>Editing Book</h1>
  <div class="error_explanation">
    <% if @book.errors.any? %>
      <h3><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h3>
      <% @book.errors.full_messages.each do |message| %>
        <ul>
          <li><%= message %></li>
        </ul>
      <% end %>
    <% end %>
  </div>
  <%= form_with model:@book, local:true do |f| %>
    <div class="form-group">
      <div class="feild_with_errors">
        <%= f.label :title, "Title" %>
      </div>
      <div class="field_with_errors">
        <%= f.text_field :title, class: "form-control book_title" %>
      </div>
    </div>
    <div class="form-group">
      <div class="field_with_errors">
        <%= f.label :body, "Opinion" %>
      </div>
      <div class="field_with_errors">
        <%= f.text_area :body, class: "form-control boo_body" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.submit 'Update Book', class: "btn btn-success" %>
    </div>
  <% end %>
  <%= link_to "Show", book_path(@book) %> |
  <%= link_to "Back", books_path %>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="error_explanation">
    <% if @book.errors.any? %>
      <h3><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h3>
      <% @book.errors.full_messages.each do |message| %>
        <ul>
          <li><%= message %></li>
        </ul>
      <% end %>
    <% end %>
  </div>
  <div class="row">
    <%= render 'books/list', user: @user %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-line">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user_id) do %>
                <%= attachment_image_tag book.user, :profile_image, fallback: "no_image.jpg", size: "40x40" %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 ps-sm-0">
  <div class="row">
    <%= render 'books/list', user: @user %>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to(user_path(@show_book.user_id)) do %>
                <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size: "40x40" %><br>
                <%= @user.name %>
              <% end %>
            </td>
            <td><%= link_to @show_book.title, book_path(@show_book.id) %></td>
            <td><%= @show_book.body %></td>
            <% if user_signed_in? && @user.id == current_user.id %>
              <td><%= link_to "Edit", edit_book_path(@show_book), class: "btn btn-sm btn-success" %></td>
              <td><%= link_to "Destroy", book_path(@show_book), class: "btn btn-sm btn-danger", method: :delete, "data-confirm" => "本当に消しますか" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcom to <i class="fas fa-book"></i><strong>Bookers</strong>!
    </h1>
  </div>
</div>

app/views/home/top.html.erb
<div class="mx-auto col-sm-10 col-lg-8 col-xl-6">
  <h1>welcomt to <i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>
  <p>In <i class="fa fa-book"></i><strong>Booksers</strong>,</p>
  <p>you can share and exchange your opinions, inpressions, and emotions</p>
  <p>about various books!</p>
  <div class="btn-wrapper col-10 mx-auto">
    <div class="row">
      <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
    </div>
    <div class="row">
      <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to " Home", user_path(current_user.id), class: 'fas fa-home nav-link text-light' %>
                </li>
                <li>
                  <%= link_to " Users", users_path, class: 'fas fa-users nav-link text-light' %>
                </li>
                <li>
                  <%= link_to " Books", books_path, class: 'fas fa-book-open nav-link text-light' %>
                </li>
                <li>
                  <%= link_to " logout", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' %>
                </li>
              <% else %>
                <li>
                  <%= link_to " Home", root_path, class: 'fas fa-home nav-link text-light' %>
                </li>
                <li>
                  <%= link_to " About", home_about_path, class: 'fas fa-link nav-link text-light' %>
                </li>
                <li>
                  <%= link_to " sign up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-light' %>
                </li>
                <li>
                  <%= link_to " login", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    
    <main>
      <p id="notice"><%= notice %></p>
      <%= yield %>
    </main>
    
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Users info</h1>
      <div class="error_explanation">
        <% if @user.errors.any? %>
          <h3><%= pluralize(@user.errors.count, "eroor") %> prohibited this obj from being saved:</h3>
          <% @user.errors.full_messages.each do |message| %>
            <ul>
              <li><%= message %></li>
            </ul>
          <% end %>
        <% end %>
      </div>
      <%= form_with model:@user, local:true do |f| %>
        <div class="form-group">
          <%= f.label :name, "Name" %>
          <%= f.text_field :name, class: "form-control name" %>
        </div>
        <div class="form-group">
          <%= f.label :profile_image, "Image" %>
          <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
        </div>
        <div class="form-group">
          <%= f.label :introduction, "Introduction" %>
          <%= f.text_field :introduction, class: "form-control introduction" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update User', class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="error_explanation">
  <% if @user.errors.any? %>
    <h3><%= pluralize(@user.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <% @user.errors.full_messages.each do |message| %>
      <ul>
        <li><%= message %></li>
      </ul>
    <% end %>
  <% end %>
</div>

<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'books/list',book:@book, user:@user %>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-line">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="1"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "40x40"  %></td>
            <td><%= user.name%></td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'books/list', user:@user %>
    <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table table-hover table-line">
      <thead>
        <tr>
          <th colspan="1"></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to(user_path(@user)) do %>
              <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size: "40x40" %>
            <% end %>
          </td>
          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </div>
</div>